// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeC2YRvntUeoeHomO1gn8AHmFN9_ILzKA',
    appId: '1:491161697808:web:e19ed841754918a7dfd495',
    messagingSenderId: '491161697808',
    projectId: 'demoproject-5cad2',
    authDomain: 'demoproject-5cad2.firebaseapp.com',
    storageBucket: 'demoproject-5cad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_z2QJB1OIE4Ub2FRYfoZAVqNWf-08dpU',
    appId: '1:491161697808:ios:5359e632ddb7afdddfd495',
    messagingSenderId: '491161697808',
    projectId: 'demoproject-5cad2',
    storageBucket: 'demoproject-5cad2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBachoFB74BCgmlz3h4H_jMhGLwAyzjomc',
    appId: '1:491161697808:android:e13850705479a848dfd495',
    messagingSenderId: '491161697808',
    projectId: 'demoproject-5cad2',
    storageBucket: 'demoproject-5cad2.firebasestorage.app',
  );

}